/**
 * Returns a state-specific regulator primer paragraph used on every city hub page.
 * Keyed by two-letter state code. Falls back to a generic paragraph for unmapped states.
 *
 * Update this map when expanding to new states so every city page in that state gets
 * the correct jurisdiction-specific copy — one edit, all cities.
 */
export function getRegulatorPrimer(stateCode: string): string {
  const code = stateCode.toUpperCase();
  const primers: Record<string, string> = {
    CA: `Memory care facilities in California are licensed as Residential Care Facilities for the Elderly (RCFEs) and regulated by the California Department of Social Services (CDSS), Community Care Licensing Division. Each facility must pass annual unannounced inspections; any citations or deficiencies are entered into the public CDSS record. Type-A deficiencies indicate immediate health and safety risk; Type-B indicate lesser violations. StarlynnCare pulls this record directly, weekly, and uses it as the primary input to every grade. Read our <a href="/methodology">full methodology</a> for detail on how each citation type is weighted.`,
    TX: `Texas assisted living facilities are regulated by the Texas Health and Human Services Commission (HHSC), Long-Term Care Regulation (LTCR). Facilities listed here carry active Alzheimer Certification where noted — that endorsement reflects dementia-capable programming on the state roster. <strong>Important:</strong> Texas ALF license Types A, B, and C describe <em>facility capability</em>; they are not the same labels as California Type-A / Type-B <em>deficiency severity</em>. Inspection findings on StarlynnCare are shown with the regulator&rsquo;s own severity text. Read our <a href="/methodology">methodology</a> and <a href="/data">data sources</a> for coverage rules.`,
    OR: `Oregon memory care facilities are licensed as Assisted Living Facilities (ALFs) or Residential Care Facilities (RCFs) and regulated by the Oregon Department of Human Services (DHS), Long-Term Care Licensing. Facilities listed here carry an active <strong>Memory Care Endorsement</strong> — a separate DHS certification requiring dedicated staff training, secured-environment protocols, and individualized dementia programming. Inspection findings (licensing violations, abuse investigations) are published on the Oregon LTC Licensing portal. StarlynnCare indexes those records directly. Read our <a href="/methodology">full methodology</a> for detail on how violations are weighted.`,
    WA: `Washington memory care facilities are Assisted Living Facilities (ALFs) regulated by the Washington State Department of Social and Health Services (DSHS), Aging and Disability Services Administration (ADSA), Residential Care Services. Facilities listed here hold an active <strong>Specialized Dementia Care contract</strong> with DSHS — a contract tier that requires dementia-specific staffing qualifications, behavioral support protocols, and enhanced supervision. Inspection and investigation reports are published publicly on the DSHS ALF Reports portal. Read our <a href="/methodology">methodology</a> and <a href="/data">data sources</a> for coverage rules.`,
    MN: `Minnesota memory care facilities are licensed as Assisted Living Facilities with Dementia Care under Minnesota Statutes ch. 144G, regulated by the Minnesota Department of Health (MDH). This licensure tier requires staff specialized in dementia care, secured environments where clinically indicated, and individualized dementia programming. Inspection and complaint findings are published by MDH. StarlynnCare indexes those records directly. Read our <a href="/methodology">full methodology</a> for detail.`,
    PA: `Pennsylvania memory care facilities are licensed as Personal Care Homes (PCH) under 55 Pa Code Chapter 2600, or Assisted Living Residences (ALR) under Chapter 2800, and regulated by the Pennsylvania Department of Human Services (DHS), Office of Long-Term Living (OLTL). Facilities listed here hold a DHS-recognized <strong>Special Care</strong> or <strong>Secure Dementia Care Unit</strong> designation, or are licensed as Assisted Living — Special Care. PA DHS publishes inspection findings in PDF format on its provider directory portal. StarlynnCare downloads, parses, and indexes every PA DHS inspection PDF for each facility profile. Read our <a href="/methodology">full methodology</a> for detail.`,
    AZ: `Arizona memory care facilities are licensed as either <strong>Assisted Living Homes (ALH, up to 10 residents)</strong> or <strong>Assisted Living Centers (ALC, 11+ residents)</strong> and regulated by the Arizona Department of Health Services (ADHS), Bureau of Residential Facilities Licensing (BRFL), under A.A.C. Title 9, Chapter 10. Facilities listed here hold an active <strong>Directed Care license level</strong> — the highest ADHS-authorized tier, required for facilities serving residents with dementia, cognitive impairment, or conditions requiring continuous supervision. ADHS confirmed in a public records response (June 2026): <em>"Arizona assisted living homes and assisted living centers licensed for directed care services are automatically authorized for memory care services."</em> Inspection records are published on AZ Care Check (azcarecheck.azdhs.gov). StarlynnCare indexes those records directly for each facility profile. Read our <a href="/methodology">full methodology</a> for detail.`,
  };
  return (
    primers[code] ??
    `Memory care facilities in this state are licensed and regulated by the relevant state health or social services authority, which conducts unannounced inspections and records deficiency findings in a public record. StarlynnCare uses this public inspection record as the primary input to every grade. Read our <a href="/methodology">full methodology</a> for detail.`
  );
}
