-- Migration 0003: Add AI-generated content column to facilities
-- The `content` column holds structured prose blocks generated by the
-- content chain and published after passing the quality gate.
--
-- Schema of the jsonb value:
--   headline                string  — short page-level tagline (≤80 chars)
--   intro                   string  — 2-3 sentence intro for families
--   memory_care_approach    string  — paragraph on the facility's MC program
--   neighborhood            string  — location/access context paragraph
--   what_families_should_know string — honest inspection-history context
--   generated_at            string  — ISO-8601 timestamp
--   model                   string  — LLM model slug used (transparency)

ALTER TABLE facilities
  ADD COLUMN IF NOT EXISTS content jsonb;

COMMENT ON COLUMN facilities.content IS
  'Structured prose content generated by the StarlynnCare content chain and '
  'published after a quality-gate pass. '
  'Keys: headline, intro, memory_care_approach, neighborhood, what_families_should_know, generated_at, model.';

-- Partial index: only index rows that have published content
CREATE INDEX IF NOT EXISTS idx_facilities_content
  ON facilities ((content IS NOT NULL))
  WHERE content IS NOT NULL;
