-- Migration 0005: add AI-generated narrative summary to inspections
-- Stores a plain-English 2-3 sentence summary of the inspector's narrative,
-- generated by Claude from the raw raw_data->>'narrative' text.

ALTER TABLE inspections
  ADD COLUMN IF NOT EXISTS narrative_summary text;

COMMENT ON COLUMN inspections.narrative_summary IS
  'Plain-English 2-3 sentence summary of the inspector narrative, generated by Claude. NULL until summarize_inspections.py has processed this record.';

CREATE INDEX IF NOT EXISTS idx_inspections_summary_null
  ON inspections (facility_id)
  WHERE narrative_summary IS NULL AND raw_data->>'narrative' IS NOT NULL;
