-- ============================================================
-- StarlynnCare Migration 0027 — Null WA Hallucinated Summaries
--
-- Removes narrative_summary values that were generated by Claude
-- from placeholder narratives ("—: WA DSHS report: Inspections (MM/YYYY)")
-- rather than from real inspector text.
--
-- Any row that matches ANY of these conditions is a hallucinated summary:
--   • raw_data->>'narrative' is NULL or empty
--   • length of raw_data->>'narrative' < 100 chars (placeholder-length)
--   • raw_data->>'narrative' starts with the known WA placeholder prefix
--
-- This is a one-shot idempotent update. Running it again is safe.
-- Facilities where PDFs are later parsed and real summaries generated
-- will simply have narrative_summary written back by summarize_inspections.py.
-- ============================================================

update inspections
set narrative_summary = null
where narrative_summary is not null
  and (
    raw_data->>'narrative' is null
    or trim(raw_data->>'narrative') = ''
    or length(trim(raw_data->>'narrative')) < 100
    or trim(raw_data->>'narrative') ~ '^—:\s*WA DSHS report:'
  );
